metadata:
  description: >-
    This task predicts whether the patient will have low _sodium_ values (hyponatremia) within the
    next 24 hours, given the first 24 hours of their admission to the _hospital_. To be included,
    1) patients must have at least one measurement for _sodium_ within the next 24 hours after their
    admission to the hospital, 2) patients must not have shown low _sodium_ values previously, and
    3) their length of stay in the hospital must be at least 48 hours.
  links: []
  contacts:
    - name: "Jungwoo Oh"
      github_username: "jwoo5"
  supported_datasets:
    - MIMIC-IV

predicates:
  hospital_admission: ???
  hospital_discharge: ???
  birth:
    code: { regex: "MEDS_BIRTH.*" }
  death:
    code: { regex: "MEDS_DEATH.*" }
  discharge_or_death:
    expr: or(death, hospital_discharge)

  # Plain predicates
  sodium_meql:
    code: ???
  abnormally_low_sodium_meql_range:
    code: null
    value_min: null
    value_max: 135 # mEq/L
    value_max_inclusive: False
  abnormally_low_sodium_meql:
    expr: and(sodium_meql, abnormally_low_sodium_meql_range)
  sodium:
    # add other units by `or(sodium_meql, ..., sodium_other_unit)`
    expr: sodium_meql
  abnormally_low_sodium:
    # add other units by `or(abnormally_low_sodium_meql, ..., abnormally_low_sodium_other_unit)`
    expr: abnormally_low_sodium_meql

trigger: hospital_admission

windows:
  input:
    start: null
    end: trigger + 24h
    start_inclusive: True
    end_inclusive: True
    index_timestamp: end
    # do not allow to have shown low sodium values previously
    has:
      abnormally_low_sodium: (None, 0)
  # do not allow hospital discharge to happen within the input + target window
  no_discharge:
    start: trigger
    end: start + 48h
    start_inclusive: False
    end_inclusive: True
    has:
      hospital_admission: (None, 0)
      discharge_or_death: (None, 0)
  # do not allow to include children (age <= 18) patients
  no_children:
    start: end - 6570d # 18 years = 365 * 18 days
    end: trigger
    start_inclusive: True
    end_inclusive: True
    has:
      birth: (None, 0)
  target:
    start: input.end
    end: start + 24h
    start_inclusive: False
    end_inclusive: True
    has:
      sodium: (1, None)
    label: abnormally_low_sodium
