metadata:
  description: >-
    This task predicts whether the patient will have low _MAP_ values (hypotension) within the next 24 hours,
    given the first 24 hours of their admission to the hospital. To be included, 1) patients must have at
    least one measurement for _MAP_ within the next 24 hours after their admission to the hospital, 2)
    patients must not have shown low _MAP_ values previously, and 3) their length of stay in the hospital must
    be at least 48 hours.
  links: []
  contacts:
    - name: "Jungwoo Oh"
      github_username: "jwoo5"
  supported_datasets:
    - MIMIC-IV

predicates:
  hospital_admission: ???
  hospital_discharge: ???
  birth:
    code: { regex: "MEDS_BIRTH.*" }
  death:
    code: { regex: "MEDS_DEATH.*" }
  discharge_or_death:
    expr: or(death, hospital_discharge)

  # Plain predicates
  map_mmhg:
    code: ???
  abnormally_low_map_mmhg_range:
    code: null
    value_min: null
    value_max: 65 # mmHg
    value_max_inclusive: False
  abnormally_low_map_mmhg:
    expr: and(map_mmhg, abnormally_low_map_mmhg_range)
  map:
    # add other units by `or(map_mmhg, ..., map_other_unit)`
    expr: map_mmhg
  abnormally_low_map:
    # add other units by `or(abnormally_low_map_mmhg, ..., abnormally_low_map_other_unit)`
    expr: abnormally_low_map_mmhg

trigger: hospital_admission

windows:
  input:
    start: null
    end: trigger + 24h
    start_inclusive: True
    end_inclusive: True
    index_timestamp: end
    # do not allow to have shown low MAP values previously
    has:
      abnormally_low_map: (None, 0)
  # do not allow hospital discharge to happen within the input + target window
  no_discharge:
    start: trigger
    end: start + 48h
    start_inclusive: False
    end_inclusive: True
    has:
      hospital_admission: (None, 0)
      discharge_or_death: (None, 0)
  # do not allow to include children (age <= 18) patients
  no_children:
    start: end - 6570d # 18 years = 365 * 18 days
    end: trigger
    start_inclusive: True
    end_inclusive: True
    has:
      birth: (None, 0)
  target:
    start: input.end
    end: start + 24h
    start_inclusive: False
    end_inclusive: True
    has:
      map: (1, None)
    label: abnormally_low_map
